DATASETS = {
    "Empresas": (
        "empresas",
        [
            "cnpj_basico",
            "razao_social",
            "natureza_juridica",
            "qualificacao_responsavel",
            "capital_social",
            "porte",
            "ente_federativo_responsavel",
        ],
    ),
    "Estabelecimentos": (
        "estabelecimentos",
        [
            "cnpj_basico",
            "cnpj_ordem",
            "cnpj_dv",
            "identificador_matriz_filial",
            "nome_fantasia",
            "situacao_cadastral",
            "data_situacao_cadastral",
            "motivo_situacao_cadastral",
            "nome_cidade_exterior",
            "pais",
            "data_inicio_atividade",
            "cnae_fiscal_principal",
            "cnaes_fiscais_secundarios",
            "tipo_logradouro",
            "logradouro",
            "numero",
            "complemento",
            "bairro",
            "cep",
            "uf",
            "municipio",
            "ddd1",
            "telefone1",
            "ddd2",
            "telefone2",
            "ddd_fax",
            "fax",
            "correio_eletronico",
            "situacao_especial",
            "data_situacao_especial",
        ],
    ),
    "Socios": (
        "socios",
        [
            "cnpj_basico",
            "identificador_socio",
            "nome_socio_razao_social",
            "cpf_cnpj_socio",
            "qualificacao_socio",
            "data_entrada_sociedade",
            "pais",
            "representante_legal",
            "nome_representante",
            "qualificacao_representante",
            "faixa_etaria",
        ],
    ),
    "Simples": (
        "simples",
        [
            "cnpj_basico",
            "opcao_simples",
            "data_opcao_simples",
            "data_exclusao_simples",
            "opcao_mei",
            "data_opcao_mei",
            "data_exclusao_mei",
        ],
    ),
    "Cnaes": ("cnaes", ["codigo", "descricao"]),
    "Municipios": ("municipios", ["codigo", "descricao"]),
    "Paises": ("paises", ["codigo", "descricao"]),
    "Naturezas": ("naturezas_juridicas", ["codigo", "descricao"]),
    "Qualificacoes": ("qualificacoes_socios", ["codigo", "descricao"]),
    "Motivos": ("motivos_situacao", ["codigo", "descricao"]),
}

DATE_COLUMNS = {
    "data_situacao_cadastral",
    "data_inicio_atividade",
    "data_situacao_especial",
    "data_entrada_sociedade",
    "data_opcao_simples",
    "data_exclusao_simples",
    "data_opcao_mei",
    "data_exclusao_mei",
}
